[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
siglab_contract = "8epbA4eCd1ieFndY5y8gZzNqmu91rMUdaY3rDVX5tZKj"

[programs.devnet]
siglab_contract = "8epbA4eCd1ieFndY5y8gZzNqmu91rMUdaY3rDVX5tZKj"

[programs.testnet]
siglab_contract = "8epbA4eCd1ieFndY5y8gZzNqmu91rMUdaY3rDVX5tZKj"

[programs.mainnet]
siglab_contract = "8epbA4eCd1ieFndY5y8gZzNqmu91rMUdaY3rDVX5tZKj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
build = "anchor build"
deploy = "anchor deploy"
upgrade = "anchor upgrade"

[test]
startup_wait = 5000

[airdrop]
amount = 2

[test.validator]
url = "https://api.devnet.solana.com"
commitment = "confirmed"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"

[[test.validator.clone]]
address = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"
